language: java
jdk: openjdk11
addons:
  sonarcloud:
    organization: "rahex-github"
    token:
       secure: d43793e9db2a9538978092fc3f6f88ecbfa265aa
script:
   - mvn clean install -DskipTests
   - mvn cobertura:cobertura
cache:
  directories:
    - "$HOME/.m2/repository"
after_success:
- bash <(curl -s https://codecov.io/bash)
